Repository hassio-addons/addon-glances, pull requests merged in 2023-03, with the labels that each got.

#323 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  glances/.README.j2
  glances/DOCS.md
Labels: maintenance

#324 ⬆️ Upgrades add-on base image to 13.1.3
  glances/Dockerfile
  glances/build.yaml
Labels: dependencies

#311 add support influxdb2 (#311)Co-authored-by: Franck Nijhof <git@frenck.dev>
  glances/DOCS.md
  glances/config.yaml
  glances/requirements.txt
  glances/rootfs/etc/cont-init.d/glances.sh
  glances/rootfs/etc/services.d/influxdb/run
Labels: new-feature

#330 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
Labels: maintenance

#329 🚑 Attempt to fix Influx Issues
  glances/DOCS.md
  glances/config.yaml
  glances/rootfs/etc/cont-init.d/glances.sh
Labels: bugfix

#335 Fix broken URLs
  glances/DOCS.md
Labels: documentation
